package it.uniroma3.ps2017.service;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import it.uniroma3.ps2017.model.Autore;
import it.uniroma3.ps2017.model.Opera;
import it.uniroma3.ps2017.model.Role;
import it.uniroma3.ps2017.model.Utente;
import it.uniroma3.ps2017.repository.AutoreRepository;
import it.uniroma3.ps2017.repository.OperaRepository;
import it.uniroma3.ps2017.repository.RoleRepository;
import it.uniroma3.ps2017.repository.UtenteRepository;

@Service
@Transactional
public class InitDbService {
	
	@Autowired
	private UtenteRepository utenteRepository;
	@Autowired
	private RoleRepository roleRepository;
	@Autowired
	private AutoreRepository autoreRepository;
	@Autowired
	private OperaRepository operaRepository;
	
	@PostConstruct
	public void init(){
		Role roleUser = new Role();
		roleUser.setRole("ROLE_USER");
		roleRepository.save(roleUser);

		Role roleAdmin = new Role();
		roleAdmin.setRole("ROLE_ADMIN");
		roleRepository.save(roleAdmin);

		Utente admin = new Utente();
		admin.setEnabled(true);
		admin.setUsername("jiripinkas");
		BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
		admin.setPassword(encoder.encode("errataaa"));	
		List<Role> roles = new ArrayList<Role>();
		roles.add(roleAdmin);
		roles.add(roleUser);
		admin.setRuoli(roles);
		utenteRepository.save(admin);
		
		Utente io = new Utente();
		io.setEnabled(true);
		io.setUsername("asdasd");
		io.setPassword(encoder.encode("asdasdasd"));
		List<Role> ruoli = new ArrayList<>();
		ruoli.add(roleUser);
		io.setRuoli(ruoli);
		utenteRepository.save(io);

		Autore ernestoManolesto = new Autore();
		ernestoManolesto.setNome("Ernesto");
		ernestoManolesto.setCognome("Manolesto");
		ernestoManolesto.setNazione("italiana");
		ernestoManolesto.setDataNascita(26, 10, 1909);
		ernestoManolesto.setDataMorte(23, 10, 2019);
		Autore julioPorrata = new Autore();
		julioPorrata.setNome("Julio");
		julioPorrata.setCognome("Porrata");
		julioPorrata.setNazione("spagnola");
		julioPorrata.setDataNascita(11, 2, 1924);
		julioPorrata.setDataMorte(28, 2, 1997);
		Autore reneTualet = new Autore();
		reneTualet.setNome("René");
		reneTualet.setCognome("Tualet");
		reneTualet.setNazione("francese");
		reneTualet.setDataNascita(30, 9, 1933);
		reneTualet.setDataMorte(4, 4, 2001);
		Autore walterWalzer = new Autore();
		walterWalzer.setNome("Walter");
		walterWalzer.setCognome("Walzer");
		walterWalzer.setNazione("austriaco");
		walterWalzer.setDataNascita(19, 9, 1934);
		walterWalzer.setDataMorte(5, 6, 1998);
		Autore heinzFreinpolizein = new Autore();
		heinzFreinpolizein.setNome("Heinz");
		heinzFreinpolizein.setCognome("Freinpolizein");
		heinzFreinpolizein.setNazione("tedesco");
		heinzFreinpolizein.setDataNascita(17, 6, 1903);
		heinzFreinpolizein.setDataMorte(19, 7, 1997);
		Autore rubenShamenns = new Autore();
		rubenShamenns.setNome("Ruben");
		rubenShamenns.setCognome("Shamenns");
		rubenShamenns.setNazione("americano");
		rubenShamenns.setDataNascita(4, 9, 1904);
		rubenShamenns.setDataMorte(17, 1, 2006);
		Autore albertoDegliAlberti = new Autore();
		albertoDegliAlberti.setNome("Alberto");
		albertoDegliAlberti.setCognome("Degli Alberti");
		albertoDegliAlberti.setNazione("italiana");
		albertoDegliAlberti.setDataNascita(6, 5, 1934);
		albertoDegliAlberti.setDataMorte(13, 6, 1995);
		Autore louisEmilthon = new Autore();
		louisEmilthon.setNome("Louis");
		louisEmilthon.setCognome("Emilthon");
		louisEmilthon.setNazione("inglese");
		louisEmilthon.setDataNascita(31, 3, 1925);
		louisEmilthon.setDataMorte(17, 9, 1992);
		Autore massimoSgravo = new Autore();
		massimoSgravo.setNome("Massimo");
		massimoSgravo.setCognome("Sgravo");
		massimoSgravo.setNazione("italiana");
		massimoSgravo.setDataNascita(14, 3, 1900);
		massimoSgravo.setDataMorte(1, 2, 1980);
		Autore guidoLacarriola = new Autore();
		guidoLacarriola.setNome("Guido");
		guidoLacarriola.setCognome("Lacarriola");
		guidoLacarriola.setNazione("italiana");
		guidoLacarriola.setDataNascita(3, 10, 1921);
		guidoLacarriola.setDataMorte(6, 6, 1984);
		
		List<Opera> opereErnesto = new ArrayList<>();
		Opera opera1 = new Opera();
		opera1.setTitolo("Le guardie e i ladri");
		opera1.setAutore(ernestoManolesto);
		opera1.setAnno(1976);
		opera1.setDimensioni("100x74");
		opera1.setTecnica("olio su pera");
		opera1.setUrl("https://cinemaitalianodatabase.files.wordpress.com/2018/02/guardia-e-ladri-scena.jpg?w=666");
		opereErnesto.add(opera1);
		Opera opera2 = new Opera();
		opera2.setTitolo("I cavalieri di Morgana");
		opera2.setAutore(ernestoManolesto);
		opera2.setAnno(1979);
		opera2.setDimensioni("96x56");
		opera2.setTecnica("pastelli incerati");
		opera2.setUrl("https://images.everyeye.it/img-notizie/i-cavalieri-zodiaco-arrivano-silver-saint-repliche-italia-2-v6-358418.jpg");
		opereErnesto.add(opera2);
		Opera opera3 = new Opera();
		opera3.setTitolo("Amici malati");
		opera3.setAutore(ernestoManolesto);
		opera3.setAnno(1968);
		opera3.setDimensioni("83x72");
		opera3.setTecnica("pennellate forti");
		opera3.setUrl("https://www.artribune.com/wp-content/uploads/2016/09/Massimo-Campigli-Le-spose-dei-marinai-1934-696x550.jpg");
		opereErnesto.add(opera3);
		
		List<Opera> opereJulio = new ArrayList<>();
		Opera opera4 = new Opera();
		opera4.setTitolo("La amalia bruta");
		opera4.setAutore(julioPorrata);
		opera4.setAnno(1992);
		opera4.setDimensioni("82x58");
		opera4.setTecnica("olio su pera");
		opera4.setUrl("https://www.culturalfemminile.com/wp-content/uploads/2019/01/1819-Lady-Selina-Meade.jpeg");
		opereJulio.add(opera4);
		Opera opera5 = new Opera();
		opera5.setTitolo("Siempre hermanos");
		opera5.setAutore(julioPorrata);
		opera5.setAnno(1961);
		opera5.setDimensioni("98x58");
		opera5.setTecnica("chiaroscuro al sole");
		opera5.setUrl("https://a.wattpad.com/cover/52879257-288-k131529.jpg");
		opereJulio.add(opera5);
		
		List<Opera> opereRene = new ArrayList<>();
		Opera opera7 = new Opera();
		opera7.setTitolo("Le alpi scoscese");
		opera7.setAutore(reneTualet);
		opera7.setAnno((int) (Math.random()*50+1960));
		opera7.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera7.setTecnica("pastelli incerati");
		opera7.setUrl("https://st.hzcdn.com/simgs/69c1603d04198025_8-2771/rustico-facciata.jpg");
		opereRene.add(opera7);
		Opera opera8 = new Opera();
		opera8.setTitolo("Solstizio del primo maggio");
		opera8.setAutore(reneTualet);
		opera8.setAnno((int) (Math.random()*50+1960));
		opera8.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera8.setTecnica("olio su pera");
		opera8.setUrl("https://services.meteored.com/img/article/big/equinozio-di-primavera-quando-nel-2020-236621-1.jpg");
		opereRene.add(opera8);
		Opera opera9 = new Opera();
		opera9.setTitolo("Gli abitanti del Congo che mangiano i cereali");
		opera9.setAutore(reneTualet);
		opera9.setAnno((int) (Math.random()*50+1960));
		opera9.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera9.setTecnica("pennellate forti");
		opera9.setUrl("https://gift-static.kxscdn.com/wp-content/uploads/2018/11/colonialismo-palma.jpg");
		opereRene.add(opera9);
		Opera opera33 = new Opera();
		opera33.setTitolo("Una domenica mattina all'isola Tiberina");
		opera33.setAutore(reneTualet);
		opera33.setAnno((int) (Math.random()*50+1960));
		opera33.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera33.setTecnica("assembramento legale");
		opera33.setUrl("https://www.it.emb-japan.go.jp/image/Isola2014/035.JPG");
		opereRene.add(opera33);
		
		List<Opera> opereWalter = new ArrayList<>();
		Opera opera10 = new Opera();
		opera10.setTitolo("Albini al sole");
		opera10.setAutore(walterWalzer);
		opera10.setAnno((int) (Math.random()*50+1960));
		opera10.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera10.setTecnica("chiaroscuro sul bianco");
		opera10.setUrl("https://www.bambino.it/wp-content/uploads/2017/10/6fb79736f375.jpg");
		opereWalter.add(opera10);
		Opera opera11 = new Opera();
		opera11.setTitolo("I cimeli di zia Ada");
		opera11.setAutore(walterWalzer);
		opera11.setAnno((int) (Math.random()*50+1960));
		opera11.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera11.setTecnica("argilla di mattoni");
		opera11.setUrl("https://i.res.24o.it/images2010/SoleOnLine5/_Immagini/Notizie/Italia/2011/12/vasi-ansa-258.jpg?uuid=34982cb8-1ce5-11e1-9ff2-6ded56993d22");
		opereWalter.add(opera11);
		Opera opera12 = new Opera();
		opera12.setTitolo("Piatti di coccio");
		opera12.setAutore(walterWalzer);
		opera12.setAnno((int) (Math.random()*50+1960));
		opera12.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera12.setTecnica("argilla di mattoni");
		opera12.setUrl("https://www.conforama.it/media/cache/app_shop_product_xlarge_thumbnail/fb/46/f1b2c6503ec408ddaf89bc9d68f2.jpeg");
		opereWalter.add(opera12);
		Opera opera13 = new Opera();
		opera13.setTitolo("Rododendri e ovini");
		opera13.setAutore(walterWalzer);
		opera13.setAnno((int) (Math.random()*50+1960));
		opera13.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera13.setTecnica("latte di capra essiccato su tela");
		opera13.setUrl("https://www.formaggi-capre-ticino.ch/images/2020/03/14/capre-mirtilli-rododendri__850x638.jpg");
		opereWalter.add(opera13);
		Opera opera14 = new Opera();
		opera14.setTitolo("Pennellate amiche");
		opera14.setAutore(walterWalzer);
		opera14.setAnno((int) (Math.random()*50+1960));
		opera14.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera14.setTecnica("pennellate forti");
		opera14.setUrl("https://image.freepik.com/vettori-gratuito/colorata-pennellate-collezione_1102-157.jpg");
		opereWalter.add(opera14);
		Opera opera15 = new Opera();
		opera15.setTitolo("Autocarri in manovra");
		opera15.setAutore(walterWalzer);
		opera15.setAnno((int) (Math.random()*50+1960));
		opera15.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera15.setTecnica("nonni al cantiere");
		opera15.setUrl("https://reggionline-obce2ympjgvjli4n.netdna-ssl.com/wp-content/uploads/2019/09/incidente-san-lazzaro-9-9-19-770x470.jpg");
		opereWalter.add(opera15);
		
		List<Opera> opereHeinz = new ArrayList<>();
		Opera opera16 = new Opera();
		opera16.setTitolo("Presine in giro");
		opera16.setAutore(heinzFreinpolizein);
		opera16.setAnno((int) (Math.random()*50+1960));
		opera16.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera16.setTecnica("uncinetto");
		opera16.setUrl("https://instamamme.net/wp-content/uploads/2016/11/FullSizeRender-25.jpg");
		opereHeinz.add(opera16);
		Opera opera17 = new Opera();
		opera17.setTitolo("Pioggia a Hockenheim");
		opera17.setAutore(heinzFreinpolizein);
		opera17.setAnno((int) (Math.random()*50+1960));
		opera17.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera17.setTecnica("acquerelli ad acqua");
		opera17.setUrl("https://www.sportfair.it/wp-content/uploads/2018/07/hockenheim-1280x720.jpg");
		opereHeinz.add(opera17);
		Opera opera18 = new Opera();
		opera18.setTitolo("Crauti grossi e crauti piccoli");
		opera18.setAutore(heinzFreinpolizein);
		opera18.setAnno((int) (Math.random()*50+1960));
		opera18.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera18.setTecnica("olio su pera");
		opera18.setUrl("https://www.peendy.com/pegaso12/wp-content/uploads/2018/03/cavolo-cappuccio-1.jpg");
		opereHeinz.add(opera18);
		Opera opera19 = new Opera();
		opera19.setTitolo("Sandali e calzini (Odio n.1)");
		opera19.setAutore(heinzFreinpolizein);
		opera19.setAnno((int) (Math.random()*50+1960));
		opera19.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera19.setTecnica("inguardabile");
		opera19.setUrl("https://www.stile.it/wp-content/uploads/2016/07/calzini.jpg");
		opereHeinz.add(opera19);
		Opera opera20 = new Opera();
		opera20.setTitolo("Pretzel scontati");
		opera20.setAutore(heinzFreinpolizein);
		opera20.setAnno((int) (Math.random()*50+1960));
		opera20.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera20.setTecnica("braccino corto");
		opera20.setUrl("https://www.myusa.it/wp-content/uploads/2020/03/ricetta-pretzel-716x403.jpg");
		opereHeinz.add(opera20);
		Opera opera21 = new Opera();
		opera21.setTitolo("Le gemme dello Jutland");
		opera21.setAutore(heinzFreinpolizein);
		opera21.setAnno((int) (Math.random()*50+1960));
		opera21.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera21.setTecnica("argilla di mattoni");
		opera21.setUrl("https://img.itinari.com/page/content/original/02634b47-7b02-42d6-bdc3-a179e1d1189a-istock-1036168710.jpg?ch=DPR&dpr=1&w=994&s=526053b971524d0bf9a1e65ad90b1cfd");
		opereHeinz.add(opera21);
		
		List<Opera> opereRuben = new ArrayList<>();
		Opera opera22 = new Opera();
		opera22.setTitolo("Tip tap fatale");
		opera22.setAutore(rubenShamenns);
		opera22.setAnno((int) (Math.random()*50+1960));
		opera22.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera22.setTecnica("agriturismo");
		opera22.setUrl("https://images2-roma.corriereobjects.it/methode_image/2015/07/11/Roma/Foto%20Gallery/2510746_MGZOOM.jpg");
		opereRuben.add(opera22);
		Opera opera23 = new Opera();
		opera23.setTitolo("Gli allevatori di marmotte");
		opera23.setAutore(rubenShamenns);
		opera23.setAnno((int) (Math.random()*50+1960));
		opera23.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera23.setTecnica("peli di pennello");
		opera23.setUrl("https://www.faidateingiardino.com/wp-content/uploads/2017/11/cane-della-prateria-domestico.jpg");
		opereRuben.add(opera23);
		Opera opera24 = new Opera();
		opera24.setTitolo("Quadro bucato");
		opera24.setAutore(rubenShamenns);
		opera24.setAnno((int) (Math.random()*50+1960));
		opera24.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera24.setTecnica("strappi su tela");
		opera24.setUrl("https://www.ilpost.it/wp-content/uploads/2015/08/11887879_1194016513957592_9130253308086509100_n.jpg");
		opereRuben.add(opera24);
		Opera opera25 = new Opera();
		opera25.setTitolo("Arte moderna morta");
		opera25.setAutore(rubenShamenns);
		opera25.setAnno((int) (Math.random()*50+1960));
		opera25.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera25.setTecnica("inguardabile");
		opera25.setUrl("https://www.hestetika.it/wp-content/uploads/2015/07/11666174_845413215527900_5463353638962491893_n.jpg");
		opereRuben.add(opera25);
		Opera opera26 = new Opera();
		opera26.setTitolo("Albicocche e prugne rubate dall'albero di quel disgraziato del mio vicino");
		opera26.setAutore(rubenShamenns);
		opera26.setAnno((int) (Math.random()*50+1960));
		opera26.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera26.setTecnica("olio su pera");
		opera26.setUrl("https://www.elisamgrading.com/downloads/categorie/immagini/medie/30.jpg");
		opereRuben.add(opera26);
		Opera opera27 = new Opera();
		opera27.setTitolo("Crampi alle ginocchia");
		opera27.setAutore(rubenShamenns);
		opera27.setAnno((int) (Math.random()*50+1960));
		opera27.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera27.setTecnica("chiaroscuro sul bianco");
		opera27.setUrl("https://ortopediaborgotaro.it/images/crampo6.png");
		opereRuben.add(opera27);
		
		List<Opera> opereAlberto = new ArrayList<>();
		Opera opera28 = new Opera();
		opera28.setTitolo("I Mangiatori di carrube");
		opera28.setAutore(albertoDegliAlberti);
		opera28.setAnno((int) (Math.random()*50+1960));
		opera28.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera28.setTecnica("abbuffata");
		opera28.setUrl("https://dc7j7i17jxn8.cloudfront.net/wp-content/uploads/2018/06/01080355/31277597_2136728449687602_1324454539834687488_n.jpg");
		opereAlberto.add(opera28);
		Opera opera29 = new Opera();
		opera29.setTitolo("Monna Raya");
		opera29.setAutore(albertoDegliAlberti);
		opera29.setAnno((int) (Math.random()*50+1960));
		opera29.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera29.setTecnica("pastelli incerati");
		opera29.setUrl("https://lh3.googleusercontent.com/proxy/mWJ6snfrpRMZtBKfGQMFE7tgxVRkFZ3q5b2__D7q0X33XdrRAouYZpSML3aUEaA1vySgeE1Z8grM6VZAy6XQLOSZqBMff9eO1WitzrfZfC-Vl3Xa7b3_vKo");
		opereAlberto.add(opera29);
		Opera opera30 = new Opera();
		opera30.setTitolo("Notte nuvolosa");
		opera30.setAutore(albertoDegliAlberti);
		opera30.setAnno((int) (Math.random()*50+1960));
		opera30.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera30.setTecnica("scattata male");
		opera30.setUrl("https://thumbs.dreamstime.com/t/nuvole-di-notte-scure-47062486.jpg");
		opereAlberto.add(opera30);
		Opera opera31 = new Opera();
		opera31.setTitolo("Il grido di crunch");
		opera31.setAutore(albertoDegliAlberti);
		opera31.setAnno((int) (Math.random()*50+1960));
		opera31.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera31.setTecnica("bocca spalancata");
		opera31.setUrl("https://i.ytimg.com/vi/BsRXIQaIVR4/hqdefault.jpg");
		opereAlberto.add(opera31);
		Opera opera32 = new Opera();
		opera32.setTitolo("Il bacetto sulla guancia");
		opera32.setAutore(albertoDegliAlberti);
		opera32.setAnno((int) (Math.random()*50+1960));
		opera32.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera32.setTecnica("labbra carnose su tela");
		opera32.setUrl("https://mery66.files.wordpress.com/2012/02/bacetto.jpg?w=225");
		opereAlberto.add(opera32);
		Opera opera34 = new Opera();
		opera34.setTitolo("La venere di Milo Cotogno");
		opera34.setAutore(albertoDegliAlberti);
		opera34.setAnno((int) (Math.random()*50+1960));
		opera34.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera34.setTecnica("blumele su pietra");
		opera34.setUrl("https://docplayer.it/docs-images/69/61365245/images/10-0.jpg");
		opereAlberto.add(opera34);
		Opera opera35 = new Opera();
		opera35.setTitolo("La morte di Marra");
		opera35.setAutore(albertoDegliAlberti);
		opera35.setAnno((int) (Math.random()*50+1960));
		opera35.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera35.setTecnica("tappeti senza tela");
		opera35.setUrl("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ0G8P4E3_ybxDQy1EdfeosGGT4UwvZr44450ZhSFCGtsIvqndg&usqp=CAU");
		opereAlberto.add(opera35);
		
		List<Opera> opereLouis = new ArrayList<>();
		Opera opera36 = new Opera();
		opera36.setTitolo("Scaricatori di porto a Genova");
		opera36.setAutore(louisEmilthon);
		opera36.setAnno((int) (Math.random()*50+1960));
		opera36.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera36.setTecnica("chiaroscuro sul bianco");
		opera36.setUrl("https://www.zeroamianto.it/sites/default/files/styles/large/public/Immagini/blog/scaricatori%20amianto%20porto%20Genova.jpg?itok=c_NtbfDj");
		opereLouis.add(opera36);
		Opera opera37 = new Opera();
		opera37.setTitolo("Apache nelle riserve delle Fiandre");
		opera37.setAutore(louisEmilthon);
		opera37.setAnno((int) (Math.random()*50+1960));
		opera37.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera37.setTecnica("poppart");
		opera37.setUrl("https://upload.wikimedia.org/wikipedia/commons/c/cd/Apache_portraits.jpg");
		opereLouis.add(opera37);
		Opera opera38 = new Opera();
		opera38.setTitolo("Gladiatori rupestri");
		opera38.setAutore(louisEmilthon);
		opera38.setAnno((int) (Math.random()*50+1960));
		opera38.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera38.setTecnica("pietra su pietra");
		opera38.setUrl("https://statics.cedscdn.it/photos/MED/12/16/4791216_1233_pompei_foto.jpg");
		opereLouis.add(opera38); 
		Opera opera39 = new Opera();
		opera39.setTitolo("Le belle rane");
		opera39.setAutore(louisEmilthon);
		opera39.setAnno((int) (Math.random()*50+1960));
		opera39.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera39.setTecnica("olio su pera");
		opera39.setUrl("https://romoletto.altervista.org/wp-content/uploads/2016/06/Rane-Interpretazione-dei-sogni.jpg");
		opereLouis.add(opera39);
		Opera opera40 = new Opera();
		opera40.setTitolo("Pescivendoli in protesta");
		opera40.setAutore(louisEmilthon);
		opera40.setAnno((int) (Math.random()*50+1960));
		opera40.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera40.setTecnica("pesci in faccia");
		opera40.setUrl("https://www.ilpost.it/wp-content/uploads/2011/07/marocco.jpg");
		opereLouis.add(opera40);
		
		List<Opera> opereMassimo = new ArrayList<>();
		Opera opera41 = new Opera();
		opera41.setTitolo("Volo dei fenicotteri rosa");
		opera41.setAutore(massimoSgravo);
		opera41.setAnno((int) (Math.random()*50+1960));
		opera41.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera41.setTecnica("pennellate astratte");
		opera41.setUrl("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQo1w2NnxekmuAQFJpFTstPdh_2LX_YmyXYa2kCgSSvjAPeZPcM&usqp=CAU");
		opereMassimo.add(opera41);
		Opera opera42 = new Opera();
		opera42.setTitolo("Il suono del grammofono");
		opera42.setAutore(massimoSgravo);
		opera42.setAnno((int) (Math.random()*50+1960));
		opera42.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera42.setTecnica("pennellate astratte");
		opera42.setUrl("https://arteeluoghi.it/images/COSTRUZIONE%20PROGRESSIVA%20100X100%202015%201.jpg");
		opereMassimo.add(opera42);
		Opera opera43 = new Opera();
		opera43.setTitolo("Natura morta");
		opera43.setAutore(massimoSgravo);
		opera43.setAnno((int) (Math.random()*50+1960));
		opera43.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera43.setTecnica("pennellate astratte");
		opera43.setUrl("https://www.artrust.ch/wp-content/uploads/2019/12/id1878.jpg");
		opereMassimo.add(opera43);
		Opera opera44 = new Opera();
		opera44.setTitolo("Mia nonna che fa la spesa");
		opera44.setAutore(massimoSgravo);
		opera44.setAnno((int) (Math.random()*50+1960));
		opera44.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera44.setTecnica("pennellate astratte");
		opera44.setUrl("https://www.pitturiamo.com/it/immagine/quadro-moderno/omaggio-a-pollock-2-70x50cm-68444.jpg");
		opereMassimo.add(opera44);
		Opera opera45 = new Opera();
		opera45.setTitolo("Cane dopo che ha morso la coda della posta");
		opera45.setAutore(massimoSgravo);
		opera45.setAnno((int) (Math.random()*50+1960));
		opera45.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera45.setTecnica("pennellate astratte");
		opera45.setUrl("https://i.pinimg.com/236x/2f/61/86/2f6186d207841798e3c49fdffe716f93.jpg");
		opereMassimo.add(opera45);
		
		List<Opera> opereGuido = new ArrayList<>();
		Opera opera6 = new Opera();
		opera6.setTitolo("Sottomarino a Catania");
		opera6.setAutore(guidoLacarriola);
		opera6.setAnno((int) (Math.random()*50+1960));
		opera6.setDimensioni((int) (Math.random()*30+80) + " " + (int) (Math.random()*30+50));
		opera6.setTecnica("acquerelli ad acqua");
		opera6.setUrl("https://www.mediterraneocronaca.it/wp-content/uploads/2019/03/Sottomarino-nucleare.jpg");
		opereGuido.add(opera6);
		Opera opera46 = new Opera();
		opera46.setTitolo("Auto ritratto");
		opera46.setAutore(guidoLacarriola);
		opera46.setAnno((int) (Math.random()*50+1960));
		opera46.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera46.setTecnica("trollate belle e buone");
		opera46.setUrl("https://liceovicogallerieditalia.files.wordpress.com/2018/02/2autofuturista.jpg?w=640");
		opereGuido.add(opera46);
		Opera opera47 = new Opera();
		opera47.setTitolo("Un vero autoritratto");
		opera47.setAutore(guidoLacarriola);
		opera47.setAnno((int) (Math.random()*50+1960));
		opera47.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera47.setTecnica("guarda come disegno male");
		opera47.setUrl("https://2.bp.blogspot.com/-4MK38g0vxvQ/VmMWD8Z3ujI/AAAAAAAAFlQ/KpLSbHLcd6o/s1600/richard-gerstl-uomo-che-ride-1908.jpg");
		opereGuido.add(opera47);
		Opera opera48 = new Opera();
		opera48.setTitolo("L'inverno magico");
		opera48.setAutore(guidoLacarriola);
		opera48.setAnno((int) (Math.random()*50+1960));
		opera48.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera48.setTecnica("pennello caldo");
		opera48.setUrl("https://www.turismo.it/fileadmin/mediafiles/multimedia/201512/images/670x400/1_2.jpg");
		opereGuido.add(opera48);
		Opera opera49 = new Opera();
		opera49.setTitolo("Mutande viola");
		opera49.setAutore(guidoLacarriola);
		opera49.setAnno((int) (Math.random()*50+1960));
		opera49.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera49.setTecnica("uncinetto");
		opera49.setUrl("https://m.media-amazon.com/images/I/81nQGPViEoL._AC_UL320_.jpg");
		opereGuido.add(opera49);
		Opera opera50 = new Opera();
		opera50.setTitolo("Le ciambelle calde al bar dell'idroscalo");
		opera50.setAutore(guidoLacarriola);
		opera50.setAnno((int) (Math.random()*50+1960));
		opera50.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera50.setTecnica("che delizia");
		opera50.setUrl("https://static.vecteezy.com/system/resources/previews/000/158/823/non_2x/vector-cute-hand-drawn-donuts.jpg");
		opereGuido.add(opera50);
		/*
		Opera opera = new Opera();
		opera.setTitolo("");
		opera.setAutore(nomeAutore);
		opera.setAnno((int) (Math.random()*50+1960));
		opera.setDimensioni((int) (Math.random()*30+80) + "x" + (int) (Math.random()*30+50));
		opera.setTecnica("");
		opera.setUrl("");
		opereDiQuellAutore.add(opera); */
		

		autoreRepository.save(ernestoManolesto);
		autoreRepository.save(julioPorrata);
		autoreRepository.save(reneTualet);
		autoreRepository.save(walterWalzer);
		autoreRepository.save(heinzFreinpolizein);
		autoreRepository.save(rubenShamenns);
		autoreRepository.save(albertoDegliAlberti);
		autoreRepository.save(louisEmilthon);
		autoreRepository.save(massimoSgravo);
		autoreRepository.save(guidoLacarriola);
		
		operaRepository.save(opera1);
		operaRepository.save(opera2);
		operaRepository.save(opera3);
		operaRepository.save(opera4);
		operaRepository.save(opera5);
		operaRepository.save(opera6);
		operaRepository.save(opera7);
		operaRepository.save(opera8);
		operaRepository.save(opera9);
		operaRepository.save(opera10);
		operaRepository.save(opera11);
		operaRepository.save(opera12);
		operaRepository.save(opera13);
		operaRepository.save(opera14);
		operaRepository.save(opera15);
		operaRepository.save(opera16);
		operaRepository.save(opera17);
		operaRepository.save(opera18);
		operaRepository.save(opera19);
		operaRepository.save(opera20);
		operaRepository.save(opera21);
		operaRepository.save(opera22);
		operaRepository.save(opera23);
		operaRepository.save(opera24);
		operaRepository.save(opera25);
		operaRepository.save(opera26);
		operaRepository.save(opera27);
		operaRepository.save(opera28);
		operaRepository.save(opera29);
		operaRepository.save(opera30);
		operaRepository.save(opera31);
		operaRepository.save(opera32);
		operaRepository.save(opera33);
		operaRepository.save(opera34);
		operaRepository.save(opera35);
		operaRepository.save(opera36);
		operaRepository.save(opera37);
		operaRepository.save(opera38);
		operaRepository.save(opera39);
		operaRepository.save(opera40);
		operaRepository.save(opera41);
		operaRepository.save(opera42);
		operaRepository.save(opera43);
		operaRepository.save(opera44);
		operaRepository.save(opera45);
		operaRepository.save(opera46);
		operaRepository.save(opera47);
		operaRepository.save(opera48);
		operaRepository.save(opera49);
		operaRepository.save(opera50);
		
	}

}
